### PR TITLE
Reading plan current day bugfix

### LINKED ISSUE #751: Reading plan "current day" gets reset
**Bug was found on And Bible version**
Build 382

**To Reproduce**
1. Start from new And Bible install
2. Open a reading plan and set to another day (e.g. go to Day 4 > Menu > Done > Click Done button, -> Reading plan window closes and day 5 has been set as current day)
3. Open reading plans again and it will open at day 5
4. Select and open another reading plan
5. Come back to the first reading plan you opened
6. It now opens on Day 1, but should have opened day 5

### PR DESCRIPTION
**Pull request by timbze**
Fixes #751

### CODE REVIEW

File: db/src/main/java/net/bible/android/database/AppDatabase.kt [hunk 1]
```diff
@@ -26,7 +26,7 @@ import net.bible.android.database.readingplan.ReadingPlanEntities
 
 import java.util.*
 
-const val DATABASE_VERSION = 32
```
Comment (tuomas2) [inline db/src/main/java/net/bible/android/database/AppDatabase.kt:29]: Version incremented but no migration?

Comment (timbze) [reply db/src/main/java/net/bible/android/database/AppDatabase.kt:29]: The migration is already there. I can find later which commit it should have been incremented, but I think this was missed.

Comment (tuomas2) [reply db/src/main/java/net/bible/android/database/AppDatabase.kt:29]: It looks like it has been forgotten indeed. Then it's okay to fix that.
