### PR TITLE
Fix MyBible red letter rendering (#2132)

### LINKED ISSUE #2132: MyBible modules do not show Red Letters properly
https://support.andbible.org/scp/tickets.php?id=1335

### PR DESCRIPTION
**Pull request by JyriWee**
## What changed
- Added MyBible red-letter feature detection in `MyBibleBook.kt`:
  - reads known info flags if present
  - falls back to detecting `<J>...</J>` markup in `verses` text
  - enables `Feature=WordsOfChrist` in generated module config when supported
- Added `app/bibleview-js/src/components/MyBible/J.vue` to render MyBible `<J>` tags through OSIS quote component with `who="jesus"`.
- Updated `OsisSegment.vue` MyBible component map to use the new `J` component.
- Added regression tests:
  - JS: MyBible `<J>` is red when `showRedLetters=true` and not red when disabled
  - Kotlin: `getConfig()` includes `Feature=WordsOfChrist` only when requested

## Benefits
- MyBible modules can now expose and render words of Jesus in red similarly to other supported modules.
- Red letters respect existing app setting (`showRedLetters`) and stay off when disabled.

## Possible side effects
- Metadata initialization for MyBible Bible modules now performs one additional lightweight lookup for `<J>` tags in `verses`.
- Modules that use non-standard red-letter markup (without `<J>` and without info flags) will still not be auto-detected.

Fixes #2132.

### CODE REVIEW

File: app/bibleview-js/src/components/MyBible/J.vue [hunk 1]
```diff
@@ -0,0 +1,31 @@
+<!--
+  - Copyright (c) 2022-2022 Martin Denham, Tuomas Airaksinen and the AndBible contributors.
```
Comment (tuomas2) [inline app/bibleview-js/src/components/MyBible/J.vue:2]: 2022

**Review by tuomas2 — APPROVED** [review]

**Comment by JyriWee** [comment]
Follow-up on Copilot suggestion in this PR:

- Optimized the WordsOfChrist fallback query by removing `lower(text)` and checking both `<J>` and `<j>` directly with `LIMIT 1`.
- Added a regression unit test for the query shape.

Implemented in PR #3671:
https://github.com/AndBible/and-bible/pull/3671
