### PR TITLE
Fix problematic coroutine of startPlan

### LINKED ISSUE #2141: Set as current day doesn't change start date
**Describe the bug**
It worked in some cases but did not work with the plan at location attached as screenshot below. Feature that start date would change was added in #2125

**Bug was found on And Bible version**
Build 643

**Screenshots**

### PR DESCRIPTION
**Pull request by Adriankhl**
I think this fixes https://github.com/AndBible/and-bible/issues/2141

Since `startPlan()` is executed in parallel, if the process is too slow
https://github.com/AndBible/and-bible/blob/051a4751d7e444ce4ef3da04d1ac483a8e03df68/app/src/main/java/net/bible/android/view/activity/readingplan/DailyReading.kt#L342
may completes after
https://github.com/AndBible/and-bible/blob/051a4751d7e444ce4ef3da04d1ac483a8e03df68/app/src/main/java/net/bible/android/view/activity/readingplan/DailyReading.kt#L345
which causes the failure of "Set as current day".

Actually I don't understand why there is a need to have coroutine in `ReadingPlanRepository`, at least how it is implemented seems to be quite error-prone.

### CODE REVIEW

**Comment by timbze** [comment]
Thank you @Adriankhl, I think you are right. I wouldn't be surprised if there were more issues like it (I was too new to coroutines when I wrote that 😦)

Did you test that it's working with this change?

**Comment by Adriankhl** [comment]
At least it seems to work on my phone (Pixel 4a 5G), I never experience the issue after the change, but you know it is quite tricky to reproduce this kind of parallel process issues.

File: app/src/main/java/net/bible/service/db/readingplan/ReadingPlanRepository.kt [hunk 1]
```diff
@@ -63,7 +63,7 @@ class ReadingPlanRepository @Inject constructor() {
     }
 
     @Synchronized
-    fun startPlan(planCode: String, date: Date = CommonUtils.truncatedDate) = scope.launch {
+    fun startPlan(planCode: String, date: Date = CommonUtils.truncatedDate) = runBlocking {
```
Comment (tuomas2) [inline app/src/main/java/net/bible/service/db/readingplan/ReadingPlanRepository.kt:66]: What does runBlocking here do differently than if we just have it as a ordinary function like

```suggestion
    fun startPlan(planCode: String, date: Date = CommonUtils.truncatedDate) {
```

?

Comment (Adriankhl) [reply app/src/main/java/net/bible/service/db/readingplan/ReadingPlanRepository.kt:66]: It is because it calls the functions `getPlan` and `updatePlan` which are suspending functions so we need the runBlocking block somewhere.

Comment (Adriankhl) [reply app/src/main/java/net/bible/service/db/readingplan/ReadingPlanRepository.kt:66]: And I just follow the style of the other functions in `ReadingPlanRepository`

Comment (tuomas2) [reply app/src/main/java/net/bible/service/db/readingplan/ReadingPlanRepository.kt:66]: Ah correct. Thanks for explanation.

**Comment by tuomas2** [comment]
This can go also to current-stable. Cherry-picking there...
