### PR TITLE
Save approximate location for non-bible documents

### LINKED ISSUE #972: Jump to offset (for non-bibles) does not work

### PR DESCRIPTION
**Pull request by tuomas2**
Will close #972

### CODE REVIEW

File: app/bibleview-js/src/components/documents/OsisDocument.vue [hunk 1]
```diff
@@ -46,6 +49,46 @@ export default {
...
+          addAnchor(node, splitText[i])
+        }
+        node.parentNode.removeChild(node);
+      }
+      return xmlDoc.firstElementChild.outerHTML;
+    }
+
+    let xml = addAnchors(osisFragment.xml);
+    xml = osisToTemplateString(xml)
+    xml = xml.replaceAll("OsisAnchorSpan", "span")
```
Comment (tuomas2) [inline app/bibleview-js/src/components/documents/OsisDocument.vue]: min webview v85

**Comment by timbze** [comment]
So far so good! Love this feature, very helpful. Thanks @tuomas2
