### PR TITLE
Bugfix AB crash after module deleted and switching tab (workspace)

### LINKED ISSUE #375: App crashes when a bible module in one of the tabs is deleted...
**Describe the bug**
AB crashes when a bible module in one of the tabs that is not in view is deleted.

**To Reproduce**
Create two tabs with two windows in each tab. first tab should have kjv and esv. For second tab use kjv,  jps
1) From the first tab, tap and hold Bible chapter, on the top left on the menu bar.
2) from the list of Bibles tap and hold JPS, then from top left of menu tap on the delete icon.
3) try to switch to second tab which use to contain jps module, the app crashes.

**Expected behavior**
Needs to be discussed.

### LINKED ISSUE #388: First Bible window is too small after adding new window
**To Reproduce**
1. Open 2 windows
2. Pull the separator bar as far down as possible
3. Close window 1 (window 2 is now the only window)
4. Add a new window

**Problem** 
The separator bar is now very high, usually behind the menu bar

**Expected behavior**
The separator bar should be centered between the 2 windows

### PR DESCRIPTION
**Pull request by timbze**
Closes #375 
Closes #388

### CODE REVIEW

File: app/src/main/java/net/bible/android/control/document/DocumentControl.kt [hunk 1]
```diff
@@ -157,6 +160,15 @@ class DocumentControl @Inject constructor(
         activeWindowPageManagerProvider.activeWindowPageManager.setCurrentDocument(newDocument)
     }
 
+    fun checkIfAnyPageDocumentsDeleted() {
+        windowControl.windowRepository.windows.filter {
+            !it.pageManager.currentBible.checkCurrentDocumentStillInstalled()
+        }.forEach {
+            it.pageManager.currentBible.currentDocument
```
Comment (tuomas2) [inline app/src/main/java/net/bible/android/control/document/DocumentControl.kt]: isn't this line unnecessary?

Comment (timbze) [reply app/src/main/java/net/bible/android/control/document/DocumentControl.kt]: Yes, you are right. Fixed
